/* ------------------------------------------------------------------
   Portfolio content — single source of truth for projects + profile.
   Consumed by projects.html (carousel) and project.html (detail view).
------------------------------------------------------------------ */

const PROFILE = {
  name: "Maneesha",
  fullName: "Maneesha Mohan N",
  email: "maneeshamohan321@gmail.com",
  phone: "+91 9745734521",
  linkedin: "https://www.linkedin.com/",
  behance: "https://www.behance.net/",
};

const PROJECTS = [
  {
    id: "logicwiz",
    no: "01",
    title: "DESIGN SYSTEM\nLOGICWIZ",
    heading: "LOGICWIZ",
    kicker: "Brand Identity / Design System",
    cover: "assets/img/logicwiz-cover.jpg",
    hero: "assets/img/logicwiz-phone.jpg",
    softwares: ["Photoshop", "Illustrator"],
    report: null,
    desc: "LogicWiz redefines technical mastery by transforming Data Structures and Algorithms into an immersive narrative experience. By blending story-driven quests, visual simulations, and AI-guided learning, the brand demystifies complex logic. My design bridges the gap between clinical code and engaging storytelling, creating an approachable, high-energy identity that turns the “grind” of computer science into a legendary quest.",
    gallery: [
      "assets/img/logicwiz-cover.jpg",
      "assets/img/logicwiz-laptop.jpg",
      "assets/img/logicwiz-grid.jpg",
      "assets/img/logicwiz-brand.jpg",
    ],
  },
  {
    id: "smart",
    no: "02",
    title: "DESIGN SYSTEM\nSMART",
    heading: "SMART — ECOSYSTEM RESTORATION",
    kicker: "Brand Identity / Design System",
    cover: "assets/img/smart-cover.jpg",
    hero: "assets/img/smart-hero.jpg",
    softwares: ["Photoshop", "Illustrator", "InDesign"],
    report: null,
    desc: "The Ecosystem Restoration Project is our urgent response to a planet at a tipping point. By reviving degraded forests, restoring freshwater systems, and integrating “green lungs” into our urban centers, we are actively reversing the damage caused by global warming and extreme climate shifts. This mission is designed to stabilize temperatures and rebuild the natural infrastructure essential for all life. By healing these ecosystems today, we are securing a resilient, healthy future for every living creation.",
    gallery: [
      "assets/img/smart-hero.jpg",
      "assets/img/smart-instagram.jpg",
      "assets/img/smart-badge.jpg",
      "assets/img/smart-cover.jpg",
    ],
  },
  {
    id: "enoc",
    no: "03",
    title: "ENOC\nSPR 2022",
    heading: "ENOC — SUSTAINABILITY PERFORMANCE REPORT 2022",
    kicker: "Annual / Sustainability Report",
    cover: "assets/img/enoc-cover.jpg",
    hero: "assets/img/enoc-cover.jpg",
    softwares: ["Photoshop", "Illustrator", "InDesign"],
    report: "https://www.enoc.com/",
    desc: "ENOC, a global leader in the energy sector — the 2022 Sustainability Performance Report highlights the company's commitment to ESG and corporate responsibility. The project focused on transforming complex energy data into a visually compelling narrative for a global audience, executed in collaboration with Stirrup Communications.",
    gallery: [
      "assets/img/enoc-cover.jpg",
      "assets/img/enoc-open.jpg",
      "assets/img/enoc-spreads.jpg",
    ],
  },
  {
    id: "icici",
    no: "04",
    title: "ICICI LOMBARD\nESG REPORT 2025",
    heading: "ICICI LOMBARD — ESG REPORT 2025",
    kicker: "ESG / Sustainability Report",
    cover: "assets/img/icici-cover.jpg",
    hero: "assets/img/icici-hero.jpg",
    softwares: ["Photoshop", "Illustrator", "InDesign", "Firefly"],
    report: "https://www.icicilombard.com/",
    desc: "ICICI Lombard, India's leading private general insurance provider — this ESG Report showcases the company's commitment to environmental, social, and governance excellence. The project involved transforming a diverse range of insurance data and corporate initiatives into a clear, visually cohesive narrative, executed in collaboration with Stirrup Communications.",
    gallery: [
      "assets/img/icici-cover.jpg",
      "assets/img/icici-hero.jpg",
      "assets/img/icici-spreads.jpg",
    ],
  },
  {
    id: "globus",
    no: "05",
    title: "GLOBUS SPIRITS\nANNUAL REPORT 2025",
    heading: "GLOBUS SPIRITS LIMITED — ANNUAL REPORT 2024-25",
    kicker: "Annual Report",
    cover: "assets/img/globus-cover.jpg",
    hero: "assets/img/globus-hero.jpg",
    softwares: ["Photoshop", "Illustrator", "InDesign", "Firefly"],
    report: "https://www.globusspirits.com/",
    desc: "Globus Spirits Limited, a high-standard leader in the spirits industry — this Annual Report highlights the company's integrated operations and commitment to stakeholder value. The project focused on transforming complex financial and operational data into a polished visual narrative that reflects both experience and innovation, executed in collaboration with Pagekraft.",
    gallery: [
      "assets/img/globus-cover.jpg",
      "assets/img/globus-open.jpg",
      "assets/img/globus-spreads.jpg",
    ],
  },
  {
    id: "sagar",
    no: "06",
    title: "SAGAR CEMENTS\nESG ROADMAP",
    heading: "SAGAR CEMENTS — ESG ROADMAP 2050",
    kicker: "ESG Roadmap",
    cover: "assets/img/sagar-cover.jpg",
    hero: "assets/img/sagar-cover.jpg",
    softwares: ["Photoshop", "Illustrator", "InDesign", "Firefly"],
    report: "https://www.sagarcements.in/",
    desc: "Sagar Cements, India's leading cement manufacturer — this project transforms their ESG Roadmap 2050 into a compelling vision. Moving beyond standard performance reporting, we visualised their long-term commitment to sustainability and stakeholder value across four decades. Executed in collaboration with Stirrup Communications, this high-impact report makes complex governance goals engaging, clear, and aspirational for a global audience.",
    gallery: [
      "assets/img/sagar-cover.jpg",
      "assets/img/sagar-open.jpg",
      "assets/img/sagar-spreads.jpg",
    ],
  },
  {
    id: "maruti",
    no: "07",
    title: "MARUTI SUZUKI\nINTEGRATED REPORT",
    heading: "MARUTI SUZUKI — INTEGRATED ANNUAL REPORT 2022-23",
    kicker: "Integrated Annual Report",
    cover: "assets/img/maruti-cover.jpg",
    hero: "assets/img/maruti-cover.jpg",
    softwares: ["Photoshop", "Illustrator", "InDesign", "Firefly"],
    report: "https://www.marutisuzuki.com/corporate/investors/annual-reports",
    desc: "This project transforms Maruti Suzuki's journey from an iconic carmaker into an experience-driven mobility leader. For their Integrated Annual Report 2022-23, we visualized the brand's evolution — from the 1983 revolution to their future-focused embrace of design and technology. Executed in collaboration with Stirrup Communications, the report captures the “Maruti Suzuki World,” showcasing their commitment to evolving consumer demands and the possibilities of tomorrow for a new generation of Indian drivers.",
    gallery: [
      "assets/img/maruti-cover.jpg",
      "assets/img/maruti-open.jpg",
      "assets/img/maruti-spreads.jpg",
    ],
  },
  {
    id: "sbi",
    no: "08",
    title: "STATE BANK OF INDIA\nANNUAL REPORT",
    heading: "STATE BANK OF INDIA — ANNUAL REPORT 2024-25",
    kicker: "Annual Report",
    cover: "assets/img/sbi-cover.jpg",
    hero: "assets/img/sbi-hero.jpg",
    softwares: ["Photoshop", "Illustrator", "InDesign", "Firefly"],
    report: "https://sbi.co.in/",
    desc: "This 2024-25 Annual Report for the State Bank of India prioritizes clarity and institutional strength. The design balances complex financial disclosures with a clean, professional aesthetic, centering on themes of resilience and modernization. By integrating dense statutory data with accessible visual storytelling, the report reinforces SBI's identity as a cornerstone of Indian finance. This project was completed while working at Stirrup Communications, delivering a sophisticated narrative for the nation's leading lender.",
    gallery: [
      "assets/img/sbi-cover.jpg",
      "assets/img/sbi-tablet.jpg",
      "assets/img/sbi-open.jpg",
      "assets/img/sbi-books.jpg",
    ],
  },
];
